# Generated by Django 5.0.2 on 2025-03-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='edate_of_admission',
            field=models.DateField(blank=True, null=True),
        ),
    ]
